public enum InputAction
{
    Move_Forward = 0,
    Back = 1,
    Move_Left = 2,
    Move_Right = 3,
    Sprint = 4,
    Jump = 5,
    Attack = 6,
    Zoom = 7,
    Down_Pet = 8,
    Previous_Pet = 9,
    Select_First_Pet = 10,
    Select_Second_Pet = 11,
    Select_Third_Pet = 12,
    Pet_Move = 13,
    Pet_Skill = 14,
    Pet_Follow = 15,
    Interaction = 16,
    Up_Pet = 17,
    Push_Object = 18,
    Pet_Skill_Up = 19,
    PickUp_And_Drop = 20,
    Throw = 21,
    Pet_Interaction = 22,
    Escape = 23,
    Pet_Move_Up = 24,
}